export const defaultLang = "en";

export type LangCode =
  | "zh-CN" | "zh-TW" | "en" | "ja" | "ko"
  | "fr" | "de" | "es" | "ru" | "pt"
  | "it" | "nl" | "pl" | "tr" | "vi"
  | "id" | "uk" | "el" | "cs" | "sv";

export const langNames: Record<LangCode, string> = {
  "zh-CN": "Simplified Chinese",
  "zh-TW": "Traditional Chinese",
  en: "English",
  ja: "Japanese",
  ko: "Korean",
  fr: "French",
  de: "German",
  es: "Spanish",
  ru: "Russian",
  pt: "Portuguese",
  it: "Italian",
  nl: "Dutch",
  pl: "Polish",
  tr: "Turkish",
  vi: "Vietnamese",
  id: "Indonesian",
  uk: "Ukrainian",
  el: "Greek",
  cs: "Czech",
  sv: "Swedish",
};

function T(en: string, translations: Partial<Record<LangCode, string>>) {
  return { en, ...translations };
}

const raw: Record<string, { en: string } & Partial<Record<LangCode, string>>> = {
  siteName: T("Hanazar Games", { "zh-CN": "哈纳扎尔工作室", "zh-TW": "哈納扎爾工作室", ja: "Hanazar Games", ko: "Hanazar Games", fr: "Hanazar Games", de: "Hanazar Games", es: "Hanazar Games", ru: "Hanazar Games", pt: "Hanazar Games", it: "Hanazar Games", nl: "Hanazar Games", pl: "Hanazar Games", tr: "Hanazar Games", vi: "Hanazar Games", id: "Hanazar Games", uk: "Hanazar Games", el: "Hanazar Games", cs: "Hanazar Games", sv: "Hanazar Games" }),
  heroEyebrow: T("Hanazar Games", { "zh-CN": "哈纳扎尔工作室", "zh-TW": "哈納扎爾工作室", ja: "Hanazar Games", ko: "Hanazar Games", fr: "Hanazar Games", de: "Hanazar Games", es: "Hanazar Games", ru: "Hanazar Games", pt: "Hanazar Games" }),
  heroTitle: T("Welcome to Hanazar Games", { "zh-CN": "欢迎来到哈纳扎尔工作室", "zh-TW": "歡迎來到哈納扎爾工作室", ja: "Hanazar Games へようこそ", ko: "Hanazar Games에 오신 것을 환영합니다", fr: "Bienvenue chez Hanazar Games", de: "Willkommen bei Hanazar Games", es: "Bienvenido a Hanazar Games", ru: "Добро пожаловать в Hanazar Games", pt: "Bem-vindo à Hanazar Games" }),
  heroSubtitle: T("A focused home for projects, documents, development notes, and the growing archive behind every world we build.", { "zh-CN": "项目、文档、开发笔记以及我们构建的每个世界背后不断成长的档案的聚焦之所。", "zh-TW": "專案、文件、開發筆記以及我們建構的每個世界背後不斷成長的檔案的聚焦之所。", ja: "プロジェクト、ドキュメント、開発ノート、そして私たちが構築するあらゆる世界の背後にある成長し続けるアーカイブのための、集中した拠点。", ko: "프로젝트, 문서, 개발 노트, 그리고 우리가 만드는 모든 세계 뒤에 성장하는 아카이브를 위한 집중된 공간입니다.", fr: "Un foyer concentré pour les projets, documents, notes de développement et l'archive croissante derrière chaque monde que nous construisons.", de: "Ein fokussiertes Zuhause für Projekte, Dokumente, Entwicklungsnotizen und das wachsende Archiv hinter jeder Welt, die wir bauen.", es: "Un hogar enfocado para proyectos, documentos, notas de desarrollo y el archivo creciente detrás de cada mundo que construimos.", ru: "Сфокусированное пространство для проектов, документов, заметок разработки и растущего архива за каждым миром, который мы создаем.", pt: "Um lar focado para projetos, documentos, notas de desenvolvimento e o arquivo crescente por trás de cada mundo que construímos." }),
  navProducts: T("Products", { "zh-CN": "产品", "zh-TW": "產品", ja: "プロダクト", ko: "제품", fr: "Produits", de: "Produkte", es: "Productos", ru: "Продукты", pt: "Produtos" }),
  navAbout: T("About", { "zh-CN": "关于", "zh-TW": "關於", ja: "概要", ko: "소개", fr: "À propos", de: "Über", es: "Acerca de", ru: "О нас", pt: "Sobre" }),
  navDocuments: T("Documents", { "zh-CN": "文档", "zh-TW": "文件", ja: "ドキュメント", ko: "문서", fr: "Documents", de: "Dokumente", es: "Documentos", ru: "Документы", pt: "Documentos" }),
  navUpdates: T("Updates", { "zh-CN": "更新", "zh-TW": "更新", ja: "更新情報", ko: "업데이트", fr: "Mises à jour", de: "Updates", es: "Actualizaciones", ru: "Обновления", pt: "Atualizações" }),
  navContact: T("Contact", { "zh-CN": "联系", "zh-TW": "聯繫", ja: "お問い合わせ", ko: "연락처", fr: "Contact", de: "Kontakt", es: "Contacto", ru: "Контакты", pt: "Contato" }),
  navSettings: T("Settings", { "zh-CN": "设置", "zh-TW": "設定", ja: "設定", ko: "설정", fr: "Paramètres", de: "Einstellungen", es: "Configuración", ru: "Настройки", pt: "Configurações" }),
  sectionProducts: T("Products", { "zh-CN": "产品", "zh-TW": "產品", ja: "プロダクト", ko: "제품", fr: "Produits", de: "Produkte", es: "Productos", ru: "Продукты", pt: "Produtos" }),
  sectionAbout: T("About HanazarGames", { "zh-CN": "关于哈纳扎尔工作室", "zh-TW": "關於哈納扎爾工作室", ja: "HanazarGames について", ko: "HanazarGames 소개", fr: "À propos de HanazarGames", de: "Über HanazarGames", es: "Acerca de HanazarGames", ru: "О HanazarGames", pt: "Sobre a HanazarGames" }),
  sectionDocuments: T("Documents", { "zh-CN": "文档", "zh-TW": "文件", ja: "ドキュメント", ko: "문서", fr: "Documents", de: "Dokumente", es: "Documentos", ru: "Документы", pt: "Documentos" }),
  sectionUpdates: T("Updates", { "zh-CN": "更新", "zh-TW": "更新", ja: "更新情報", ko: "업데이트", fr: "Mises à jour", de: "Updates", es: "Actualizaciones", ru: "Обновления", pt: "Atualizações" }),
  sectionContact: T("Contact", { "zh-CN": "联系", "zh-TW": "聯繫", ja: "お問い合わせ", ko: "연락처", fr: "Contact", de: "Kontakt", es: "Contacto", ru: "Контакты", pt: "Contato" }),
  productFeaturedTitle: T("Featured Title", { "zh-CN": "精选作品", "zh-TW": "精選作品", ja: "注目作品", ko: "주요 작품", fr: "Titre en vedette", de: "Haupttitel", es: "Título destacado", ru: "Избранное", pt: "Título em destaque" }),
  productFeaturedBody: T("Use this card for your main project showcase, store link, or the game you want visitors to see first.", { "zh-CN": "在此卡片展示你的主打项目、商店链接或希望访客首先看到的游戏。", "zh-TW": "在此卡片展示你的主打專案、商店連結或希望訪客首先看到的遊戲。", ja: "メインプロジェクト、ストアリンク、または訪問者に最初に見てほしいゲームを紹介するカードです。", ko: "주요 프로젝트, 스토어 링크 또는 방문자가 먼저 보기를 원하는 게임을 이 카드에 표시하세요.", fr: "Utilisez cette carte pour votre vitrine de projet principal, lien de magasin, ou le jeu que vous voulez que les visiteurs voient en premier.", de: "Verwenden Sie diese Karte für Ihre Hauptprojekt-Showcase, Store-Link oder das Spiel, das Besucher zuerst sehen sollen.", es: "Usa esta tarjeta para tu escaparate principal de proyecto, link de tienda o el juego que quieres que los visitantes vean primero.", ru: "Используйте эту карточку для основного проекта, ссылки на магазин или игры, которую вы хотите, чтобы посетители увидели первой.", pt: "Use este cartão para sua vitrine principal de projeto, link de loja ou o jogo que você quer que os visitantes vejam primeiro." }),
  productWorldsTitle: T("Games Hub", { "zh-CN": "游戏合集", "zh-TW": "遊戲合集", ja: "ゲームハブ", ko: "게임 허브", fr: "Hub de jeux", de: "Spiele-Hub", es: "Hub de juegos", ru: "Игровой хаб", pt: "Hub de jogos" }),
  productWorldsBody: T("A collection of browser-based mini-games — Tic-Tac-Toe, Minesweeper, and 3D 2048. Click to play directly in your browser.", { "zh-CN": "浏览器即玩小游戏合集 — 井字棋、扫雷、3D 2048。点击即可在浏览器中直接游玩。", "zh-TW": "瀏覽器即玩小遊戲合集 — 井字棋、踩地雷、3D 2048。點擊即可在瀏覽器中直接遊玩。", ja: "ブラウザベースのミニゲーム集 — tic-tac-toe、マインスイーパー、3D 2048。クリックすればブラウザで直接プレイできます。", ko: "브라우저 기반 미니 게임 모음 — 틱택토, 지뢰찾기, 3D 2048. 클릭하면 브라우저에서 바로 플레이할 수 있습니다.", fr: "Une collection de mini-jeux basés sur navigateur — Tic-Tac-Toe, Démineur et 2048 3D. Cliquez pour jouer directement dans votre navigateur.", de: "Eine Sammlung browserbasierter Minispiele — Tic-Tac-Toe, Minesweeper und 3D 2048. Klicken Sie, um direkt im Browser zu spielen.", es: "Una colección de minijuegos basados en navegador — Tic-Tac-Toe, Buscaminas y 2048 3D. Haz clic para jugar directamente en tu navegador.", ru: "Коллекция мини-игр в браузере — крестики-нолики, сапер и 3D 2048. Нажмите, чтобы играть прямо в браузере.", pt: "Uma coleção de minijogos baseados em navegador — Jogo da Velha, Campo Minado e 2048 3D. Clique para jogar diretamente no seu navegador." }),
  productConceptsTitle: T("Playable Concepts", { "zh-CN": "可玩概念", "zh-TW": "可玩概念", ja: "プレイアブルコンセプト", ko: "플레이어블 컨셉", fr: "Concepts jouables", de: "Spielbare Konzepte", es: "Conceptos jugables", ru: "Игровые концепции", pt: "Conceitos jogáveis" }),
  productConceptsBody: T("Use this module for prototypes, upcoming releases, or experimental ideas that you want to surface early.", { "zh-CN": "用于展示原型、即将发布的作品或希望提前公开的实验性创意。", "zh-TW": "用於展示原型、即將發布的作品或希望提前公開的實驗性創意。", ja: "プロトタイプ、近日公開予定の作品、または早期に公開したい実験的なアイデアのためのモジュールです。", ko: "프로토타입, 예정된 출시 또는 일찍 공개하고 싶은 실험적인 아이디어를 위한 모듈입니다.", fr: "Utilisez ce module pour les prototypes, les sorties à venir ou les idées expérimentales que vous voulez mettre en avant tôt.", de: "Verwenden Sie dieses Modul für Prototypen, kommende Veröffentlichungen oder experimentelle Ideen, die Sie früh präsentieren möchten.", es: "Usa este módulo para prototipos, lanzamientos próximos o ideas experimentales que quieras mostrar temprano.", ru: "Используйте этот модуль для прототипов, предстоящих релизов или экспериментальных идей, которые вы хотите показать заранее.", pt: "Use este módulo para protótipos, lançamentos futuros ou ideias experimentais que você quer revelar cedo." }),
  ctaViewGithub: T("View GitHub", { "zh-CN": "查看 GitHub", "zh-TW": "查看 GitHub", ja: "GitHub を見る", ko: "GitHub 보기", fr: "Voir GitHub", de: "GitHub ansehen", es: "Ver GitHub", ru: "Посмотреть GitHub", pt: "Ver GitHub" }),
  ctaPlayNow: T("Play Now", { "zh-CN": "立即游玩", "zh-TW": "立即遊玩", ja: "今すぐプレイ", ko: "지금 플레이", fr: "Jouer maintenant", de: "Jetzt spielen", es: "Jugar ahora", ru: "Играть сейчас", pt: "Jogar agora" }),
  aboutBody1: T("Hanazar Games is an independent game studio built around atmosphere, strong visual identity, and worlds that feel deliberate from the first screen to the final detail.", { "zh-CN": "哈纳扎尔工作室是一家独立游戏工作室，以氛围感、强烈的视觉辨识度和从第一屏到最后一处细节都经过深思熟虑的世界为核心。", "zh-TW": "哈納扎爾工作室是一家獨立遊戲工作室，以氛圍感、強烈的視覺辨識度和從第一屏到最後一處細節都經過深思熟慮的世界為核心。", ja: "Hanazar Games は、雰囲気、強い視覚的アイデンティティ、そして最初の画面から最後のディテールまで意図的に感じられる世界を中心に構築されたインディーゲームスタジオです。", ko: "Hanazar Games는 분위기, 강력한 시각적 정체성, 그리고 첫 화면부터 마지막 디테일까지 의도적으로 느껴지는 세계를 중심으로 구축된 인디 게임 스튜디오입니다.", fr: "Hanazar Games est un studio de jeux indépendant construit autour de l'atmosphère, d'une forte identité visuelle et de mondes qui se sentent délibérés du premier écran au dernier détail.", de: "Hanazar Games ist ein unabhängiges Spielestudio, das auf Atmosphäre, starke visuelle Identität und Welten aufbaut, die vom ersten Bildschirm bis zum letzten Detail durchdacht wirken.", es: "Hanazar Games es un estudio de juegos independiente construido alrededor de la atmósfera, una fuerte identidad visual y mundos que se sienten deliberados desde la primera pantalla hasta el último detalle.", ru: "Hanazar Games — независимая игровая студия, построенная вокруг атмосферы, сильной визуальной идентичности и миров, которые кажутся продуманными с первого экрана до последней детали.", pt: "Hanazar Games é um estúdio de jogos independente construído em torno da atmosfera, forte identidade visual e mundos que parecem deliberados da primeira tela ao último detalhe." }),
  aboutBody2: T("This site is designed to grow into a central archive for our projects, development notes, internal thinking, and the public-facing material around each release.", { "zh-CN": "本网站旨在成长为项目、开发笔记、内部思考以及每次发布周边公开资料的中央档案库。", "zh-TW": "本網站旨在成長為專案、開發筆記、內部思考以及每次發布周邊公開資料的中央檔案庫。", ja: "このサイトは、プロジェクト、開発ノート、内部的な思考、および各リリース周辺の公開資料の中央アーカイブへと成長することを目的に設計されています。", ko: "이 사이트는 프로젝트, 개발 노트, 내부적인 사고, 그리고 각 출시 주변의 공개 자료를 위한 중앙 아카이브로 성장하도록 설계되었습니다.", fr: "Ce site est conçu pour devenir une archive centrale pour nos projets, notes de développement, réflexions internes et le matériel public autour de chaque sortie.", de: "Diese Website soll zu einem zentralen Archiv für unsere Projekte, Entwicklungsnotizen, internes Denken und das öffentliche Material rund um jede Veröffentlichung heranwachsen.", es: "Este sitio está diseñado para crecer en un archivo central para nuestros proyectos, notas de desarrollo, pensamiento interno y el material público alrededor de cada lanzamiento.", ru: "Этот сайт создан для того, чтобы стать центральным архивом наших проектов, заметок разработки, внутренних размышлений и публичных материалов вокруг каждого релиза.", pt: "Este site é projetado para crescer em um arquivo central para nossos projetos, notas de desenvolvimento, pensamento interno e o material público em torno de cada lançamento." }),
  aboutBody3: T("The visual language stays restrained and monochrome so the work itself stays in focus while the structure remains scalable for future content.", { "zh-CN": "视觉语言保持克制与单色，让作品本身保持焦点，同时结构具备未来内容扩展的弹性。", "zh-TW": "視覺語言保持克制與單色，讓作品本身保持焦點，同時結構具備未來內容擴展的彈性。", ja: "視覚言語は抑制されモノクロームであり、作品そのものに焦点を当てながら、将来のコンテンツに対してスケーラブルな構造を維持します。", ko: "시각 언어는 절제되고 단색으로 유지되어 작품 자체가 초점을 유지하면서 구조는 미래 콘텐츠에 대해 확장 가능합니다.", fr: "Le langage visuel reste sobre et monochrome pour que l'œuvre elle-même reste au centre de l'attention tandis que la structure reste évolutive pour le contenu futur.", de: "Die visuelle Sprache bleibt zurückhaltend und monochrom, damit die Arbeit selbst im Fokus bleibt, während die Struktur für zukünftige Inhalte skalierbar bleibt.", es: "El lenguaje visual se mantiene contenido y monocromo para que la obra misma permanezca en foco mientras la estructura permanece escalable para contenido futuro.", ru: "Визуальный язык остается сдержанным и монохромным, чтобы сама работа оставалась в фокусе, а структура оставалась масштабируемой для будущего контента.", pt: "A linguagem visual permanece contida e monocromática para que a obra em si permaneça em foco enquanto a estrutura permanece escalável para conteúdo futuro." }),
};

// remaining keys
raw.docDesignTitle = T("Design Docs", { "zh-CN": "设计文档", "zh-TW": "設計文件", ja: "設計ドキュメント", ko: "디자인 문서", fr: "Docs de conception", de: "Designdokumente", es: "Documentos de diseño", ru: "Дизайн-документы", pt: "Documentos de design", it: "Documenti di design", nl: "Ontwerpdocumenten", pl: "Dokumenty projektowe", tr: "Tasarım Dokümanları", vi: "Tài liệu thiết kế", id: "Dokumen Desain", uk: "Дизайн-документи", el: "Έγγραφα Σχεδιασμού", cs: "Návrhové dokumenty", sv: "Designdokument" });
raw.docDesignBody = T("Gameplay structure, mechanics breakdowns, loop design, and system planning.", { "zh-CN": "游戏玩法结构、机制拆解、循环设计与系统规划。", "zh-TW": "遊戲玩法結構、機制拆解、循環設計與系統規劃。", ja: "ゲームプレイ構造、メカニクスの分解、ループ設計、システム計画。", ko: "게임플레이 구조, 메커니즘 분석, 루프 설계, 시스템 계획.", fr: "Structure du gameplay, analyses de mécaniques, conception de boucles et planification système.", de: "Spielstruktur, Mechanik-Aufschlüsselungen, Loop-Design und Systemplanung.", es: "Estructura de gameplay, análisis de mecánicas, diseño de bucles y planificación de sistemas.", ru: "Структура геймплея, разбор механик, дизайн циклов и системное планирование.", pt: "Estrutura de gameplay, análises de mecânicas, design de loops e planejamento de sistemas.", it: "Struttura del gameplay, analisi delle meccaniche, design dei loop e pianificazione dei sistemi.", nl: "Gameplay-structuur, mechaniek-uitwerkingen, loop-ontwerp en systeemplanning.", pl: "Struktura rozgrywki, analiza mechanik, projektowanie pętli i planowanie systemów.", tr: "Oynanış yapısı, mekanik analizleri, döngü tasarımı ve sistem planlama.", vi: "Cấu trúc lối chơi, phân tích cơ chế, thiết kế vòng lặp và lập kế hoạch hệ thống.", id: "Struktur gameplay, analisis mekanik, desain loop, dan perencanaan sistem.", uk: "Структура геймплею, розбір механік, дизайн циклів та системне планування.", el: "Δομή gameplay, ανάλυση μηχανικών, σχεδίαση βρόχων και προγραμματισμός συστημάτων.", cs: "Struktura hratelnosti, rozbor mechanik, návrh smyček a systémové plánování.", sv: "Spelstruktur, mekanikanalyser, loopdesign och systemplanering." });
raw.docLoreTitle = T("Lore Notes", { "zh-CN": "世界观笔记", "zh-TW": "世界觀筆記", ja: "世界観ノート", ko: "세계관 노트", fr: "Notes de lore", de: "Lore-Notizen", es: "Notas de lore", ru: "Заметки о лоре", pt: "Notas de lore", it: "Note sul lore", nl: "Lore-notities", pl: "Notatki o lore", tr: "Lore Notları", vi: "Ghi chú cốt truyện", id: "Catatan Lore", uk: "Нотатки про всесвіт", el: "Σημειώσεις Lore", cs: "Lore poznámky", sv: "Lore-anteckningar" });
raw.docLoreBody = T("Setting history, worldbuilding fragments, naming systems, and narrative references.", { "zh-CN": "设定历史、世界观碎片、命名系统与叙事参考。", "zh-TW": "設定歷史、世界觀碎片、命名系統與敘事參考。", ja: "設定の歴史、世界構築の断片、命名システム、物語の参照。", ko: "설정 역사, 세계관 조각, 명명 시스템, 서사 참고 자료.", fr: "Histoire de l'univers, fragments de worldbuilding, systèmes de nommage et références narratives.", de: "Setting-Geschichte, Worldbuilding-Fragmente, Namenssysteme und narrative Referenzen.", es: "Historia del setting, fragmentos de worldbuilding, sistemas de nombres y referencias narrativas.", ru: "История сеттинга, фрагменты ворлдбилдинга, системы именования и повествовательные референсы.", pt: "História do cenário, fragmentos de construção de mundos, sistemas de nomenclatura e referências narrativas.", it: "Storia del setting, frammenti di worldbuilding, sistemi di denominazione e riferimenti narrativi.", nl: "Setting-geschiedenis, worldbuilding-fragmenten, naamgevingssystemen en narratieve referenties.", pl: "Historia świata, fragmenty budowania świata, systemy nazewnictwa i odniesienia narracyjne.", tr: "Evren tarihi, dünya oluşturma parçacıkları, isimlendirme sistemleri ve anlatı referansları.", vi: "Lịch sử bối cảnh, mảnh ghép thế giới, hệ thống đặt tên và tài liệu tham khảo cốt truyện.", id: "Sejarah pengaturan, fragmen pembangunan dunia, sistem penamaan, dan referensi naratif.", uk: "Історія сеттінгу, фрагменти світобудування, системи іменування та наративні референси.", el: "Ιστορία σκηνικού, θραύσματα κατασκευής κόσμου, συστήματα ονοματοδοσίας και αφηγηματικές αναφορές.", cs: "Historie světa, fragmenty budování světa, systémy pojmenování a narativní reference.", sv: "Setting-historia, worldbuilding-fragment, namngivningssystem och narrativa referenser." });
raw.docVisualTitle = T("Visual Direction", { "zh-CN": "视觉方向", "zh-TW": "視覺方向", ja: "視覚方向性", ko: "시각 방향", fr: "Direction visuelle", de: "Visuelle Richtung", es: "Dirección visual", ru: "Визуальное направление", pt: "Direção visual", it: "Direzione visiva", nl: "Visuele richting", pl: "Kierunek wizualny", tr: "Görsel Yön", vi: "Hướng thị giác", id: "Arah Visual", uk: "Візуальний напрямок", el: "Οπτική Κατεύθυνση", cs: "Vizuální směr", sv: "Visuell riktning" });
raw.docVisualBody = T("Moodboards, UI direction, color studies, layout standards, and brand language.", { "zh-CN": "情绪板、UI方向、色彩研究、布局标准与品牌语言。", "zh-TW": "情緒板、UI方向、色彩研究、布局標準與品牌語言。", ja: "ムードボード、UI方向性、色彩研究、レイアウト標準、ブランド言語。", ko: "무드보드, UI 방향, 색채 연구, 레이아웃 표준, 브랜드 언어.", fr: "Planches d'ambiance, direction UI, études de couleur, standards de mise en page et langage de marque.", de: "Moodboards, UI-Richtung, Farbstudien, Layout-Standards und Markensprache.", es: "Moodboards, dirección de UI, estudios de color, estándares de layout y lenguaje de marca.", ru: "Мудборды, направление UI, цветовые исследования, стандарты макетов и брендовый язык.", pt: "Moodboards, direção de UI, estudos de cor, padrões de layout e linguagem de marca.", it: "Moodboard, direzione UI, studi cromatici, standard di layout e linguaggio del brand.", nl: "Moodboards, UI-richting, kleurstudies, layout-standaarden en merk-taal.", pl: "Moodboardy, kierunek UI, studia kolorów, standardy układu i język marki.", tr: "Moodboardlar, UI yönü, renk çalışmaları, düzen standartları ve marka dili.", vi: "Bảng tâm trạng, hướng UI, nghiên cứu màu sắc, tiêu chuẩn bố cục và ngôn ngữ thương hiệu.", id: "Moodboard, arah UI, studi warna, standar tata letak, dan bahasa merek.", uk: "Мудборди, напрямок UI, колористичні студії, стандарти макетів та брендова мова.", el: "Moodboards, κατεύθυνση UI, μελέτες χρωμάτων, πρότυπα διάταξης και γλώσσα εμπορικού σήματος.", cs: "Moodboardy, směr UI, barevné studie, standardy rozvržení a jazyk značky.", sv: "Moodboards, UI-riktning, färgstudier, layoutstandarder och varumärkesspråk." });
raw.updateDevlogTitle = T("Devlog", { "zh-CN": "开发日志", "zh-TW": "開發日誌", ja: "開発日誌", ko: "개발 일지", fr: "Devlog", de: "Devlog", es: "Devlog", ru: "Девлог", pt: "Devlog", it: "Devlog", nl: "Devlog", pl: "Devlog", tr: "Geliştirme Günlüğü", vi: "Nhật ký phát triển", id: "Devlog", uk: "Девлог", el: "Devlog", cs: "Devlog", sv: "Utvecklingslogg" });
raw.updateDevlogBody = T("A living stream of progress, experiments, milestones, and production snapshots.", { "zh-CN": "进度、实验、里程碑与生产快照的实时流。", "zh-TW": "進度、實驗、里程碑與生產快照的即時流。", ja: "進捗、実験、マイルストーン、制作スナップショットの生の流れ。", ko: "진행 상황, 실험, 이정표, 제작 스냅샷의 생생한 흐름.", fr: "Un flux vivant de progrès, d'expérimentations, de jalons et de captures de production.", de: "Ein lebendiger Strom von Fortschritt, Experimenten, Meilensteinen und Produktionsschnappschüssen.", es: "Un flujo vivo de progreso, experimentos, hitos y capturas de producción.", ru: "Живой поток прогресса, экспериментов, вех и производственных снимков.", pt: "Um fluxo vivo de progresso, experimentos, marcos e capturas de produção.", it: "Un flusso vivo di progressi, esperimenti, traguardi e istantanee di produzione.", nl: "Een levende stroom van voortgang, experimenten, mijlpalen en productiesnapshots.", pl: "Żywy strumień postępów, eksperymentów, kamieni milowych i migawek produkcyjnych.", tr: "İlerleme, deneyler, dönüm noktaları ve üretim anlık görüntülerinin canlı akışı.", vi: "Luồng thông tin trực tiếp về tiến độ, thử nghiệm, cột mốc và ảnh chụp sản xuất.", id: "Aliran langsung kemajuan, eksperimen, tonggak sejarah, dan cuplikan produksi.", uk: "Живий потік прогресу, експериментів, етапів та виробничих знімків.", el: "Μια ζωντανή ροή προόδου, πειραμάτων, οροσήμων και στιγμιοτύπων παραγωγής.", cs: "Živý proud pokroku, experimentů, milníků a produkčních snímků.", sv: "En levande ström av framsteg, experiment, milstolpar och produktionsskärmdumpar." });
raw.updateReleaseTitle = T("Release Notes", { "zh-CN": "更新日志", "zh-TW": "更新日誌", ja: "リリースノート", ko: "릴리스 노트", fr: "Notes de version", de: "Versionshinweise", es: "Notas de lanzamiento", ru: "Примечания к релизу", pt: "Notas de lançamento", it: "Note di rilascio", nl: "Release-opmerkingen", pl: "Informacje o wydaniu", tr: "Sürüm Notları", vi: "Ghi chú phát hành", id: "Catatan Rilis", uk: "Примітки до релізу", el: "Σημειώσεις Έκδοσης", cs: "Poznámky k vydání", sv: "Versionsanteckningar" });
raw.updateReleaseBody = T("Patch notes, version summaries, feature additions, and change history.", { "zh-CN": "补丁说明、版本摘要、功能新增与变更历史。", "zh-TW": "補丁說明、版本摘要、功能新增與變更歷史。", ja: "パッチノート、バージョン概要、機能追加、変更履歴。", ko: "패치 노트, 버전 요약, 기능 추가, 변경 이력.", fr: "Notes de patch, résumés de version, ajouts de fonctionnalités et historique des modifications.", de: "Patchnotizen, Versionszusammenfassungen, Feature-Hinzufügungen und Änderungshistorie.", es: "Notas de parche, resúmenes de versión, adiciones de características e historial de cambios.", ru: "Патч-ноуты, сводки версий, добавление функций и история изменений.", pt: "Notas de patch, resumos de versão, adições de recursos e histórico de alterações.", it: "Note patch, riassunti versione, aggiunte di funzionalità e cronologia delle modifiche.", nl: "Patchnotities, versiesamenvattingen, toevoegingen van functies en wijzigingsgeschiedenis.", pl: "Notatki poprawek, podsumowania wersji, dodawanie funkcji i historia zmian.", tr: "Yama notları, sürüm özetleri, özellik eklemeleri ve değişiklik geçmişi.", vi: "Ghi chú bản vá, tóm tắt phiên bản, bổ sung tính năng và lịch sử thay đổi.", id: "Catatan patch, ringkasan versi, penambahan fitur, dan riwayat perubahan.", uk: "Патч-ноути, підсумки версій, додавання функцій та історія змін.", el: "Σημειώσεις patch, περιλήψεις εκδόσεων, προσθήκες λειτουργιών και ιστορικό αλλαγών.", cs: "Poznámky k opravám, shrnutí verzí, přidání funkcí a historie změn.", sv: "Patchanteckningar, versionssammanfattningar, funktionsadditioner och ändringshistorik." });
raw.updateNewsTitle = T("Studio News", { "zh-CN": "工作室新闻", "zh-TW": "工作室新聞", ja: "スタジオニュース", ko: "스튜디오 뉴스", fr: "Actualités du studio", de: "Studio-News", es: "Noticias del estudio", ru: "Новости студии", pt: "Notícias do estúdio", it: "Notizie dello studio", nl: "Studio-nieuws", pl: "Aktualności studia", tr: "Stüdyo Haberleri", vi: "Tin tức Studio", id: "Berita Studio", uk: "Новини студії", el: "Νέα Στούντιο", cs: "Zprávy studia", sv: "Studio-nyheter" });
raw.updateNewsBody = T("Announcements, roadmap moments, festival news, and public updates from the team.", { "zh-CN": "公告、路线图节点、展会新闻与团队公开更新。", "zh-TW": "公告、路線圖節點、展會新聞與團隊公開更新。", ja: "アナウンス、ロードマップの節目、フェスティバルニュース、チームからの公開アップデート。", ko: "공지사항, 로드맵 순간, 페스티벌 뉴스, 팀의 공개 업데이트.", fr: "Annonces, moments de feuille de route, nouvelles de festivals et mises à jour publiques de l'équipe.", de: "Ankündigungen, Roadmap-Momente, Festival-Neuigkeiten und öffentliche Updates vom Team.", es: "Anuncios, momentos de hoja de ruta, noticias de festivales y actualizaciones públicas del equipo.", ru: "Анонсы, этапы дорожной карты, фестивальные новости и публичные обновления от команды.", pt: "Anúncios, momentos de roteiro, notícias de festivais e atualizações públicas da equipe.", it: "Annunci, momenti della roadmap, notizie sui festival e aggiornamenti pubblici dal team.", nl: "Aankondigingen, roadmap-momenten, festivalnieuws en publieke updates van het team.", pl: "Ogłoszenia, momenty z planu działania, wiadomości z festiwali i publiczne aktualizacje zespołu.", tr: "Duyurular, yol haritası anları, festival haberleri ve ekipten kamuya açık güncellemeler.", vi: "Thông báo, các mốc lộ trình, tin tức lễ hội và cập nhật công khai từ nhóm.", id: "Pengumuman, momen peta jalan, berita festival, dan pembaruan publik dari tim.", uk: "Анонси, етапи дорожньої карти, фестивальні новини та публічні оновлення від команди.", el: "Ανακοινώσεις, στιγμές οδικού χάρτη, νέα φεστιβάλ και δημόσιες ενημερώσεις από την ομάδα.", cs: "Oznámení, milníky plánu, festivalové zprávy a veřejné aktualizace od týmu.", sv: "Tillkännagivanden, roadmap-ögonblick, festivalnyheter och offentliga uppdateringar från teamet." });
raw.contactSteamTitle = T("Steam", { "zh-CN": "Steam", "zh-TW": "Steam", ja: "Steam", ko: "Steam", fr: "Steam", de: "Steam", es: "Steam", ru: "Steam", pt: "Steam", it: "Steam", nl: "Steam", pl: "Steam", tr: "Steam", vi: "Steam", id: "Steam", uk: "Steam", el: "Steam", cs: "Steam", sv: "Steam" });
raw.contactSteamBody = T("Direct players to your store page, game hub, or current featured release.", { "zh-CN": "引导玩家前往商店页面、游戏中心或当前主打发布。", "zh-TW": "引導玩家前往商店頁面、遊戲中心或當前主打發布。", ja: "プレイヤーをストアページ、ゲームハブ、または現在の注目リリースへ誘導します。", ko: "스토어 페이지, 게임 허브 또는 현재 주요 출시로 플레이어를 안내합니다.", fr: "Dirigez les joueurs vers votre page de magasin, hub de jeu ou sortie en vedette actuelle.", de: "Leiten Sie Spieler zu Ihrer Store-Seite, Ihrem Game-Hub oder Ihrer aktuellen Hauptveröffentlichung.", es: "Dirige a los jugadores a tu página de tienda, hub de juegos o lanzamiento destacado actual.", ru: "Направьте игроков на страницу магазина, игровой хаб или текущий избранный релиз.", pt: "Direcione jogadores para sua página de loja, hub de jogo ou lançamento em destaque atual.", it: "Dirigi i giocatori alla tua pagina del negozio, hub di gioco o uscita in primo piano attuale.", nl: "Leid spelers naar je store-pagina, gamehub of huidige uitgelichte release.", pl: "Skieruj graczy do swojej strony sklepu, centrum gry lub aktualnego wyróżnionego wydania.", tr: "Oyuncuları mağaza sayfanıza, oyun merkezinize veya mevcut öne çıkan sürümünüze yönlendirin.", vi: "Hướng người chơi đến trang cửa hàng, trung tâm trò chơi hoặc bản phát hành nổi bật hiện tại của bạn.", id: "Arahkan pemain ke halaman toko, pusat permainan, atau rilis unggulan Anda saat ini.", uk: "Направте гравців на сторінку магазину, ігровий хаб або поточний вибраний реліз.", el: "Κατευθύνετε τους παίκτες στη σελίδα του καταστήματός σας, τον κόμβο παιχνιδιού ή την τρέχουσα προβεβλημένη κυκλοφορία.", cs: "Nasměrujte hráče na svou stránku obchodu, herní rozbočovač nebo aktuální doporučené vydání.", sv: "Dirigera spelare till din butikssida, spelhub eller aktuell utvald release." });
raw.contactBusinessTitle = T("Business", { "zh-CN": "商务", "zh-TW": "商務", ja: "ビジネス", ko: "비즈니스", fr: "Business", de: "Business", es: "Negocios", ru: "Бизнес", pt: "Negócios", it: "Business", nl: "Zakelijk", pl: "Biznes", tr: "İş", vi: "Kinh doanh", id: "Bisnis", uk: "Бізнес", el: "Επιχείρηση", cs: "Podnikání", sv: "Företag" });
raw.contactBusinessBody = T("Reserve this area for partnerships, press, publishing inquiries, or contact mail.", { "zh-CN": "预留区域用于合作、媒体、发行咨询或联系邮件。", "zh-TW": "預留區域用於合作、媒體、發行諮詢或聯繫郵件。", ja: "パートナーシップ、プレス、出版の問い合わせ、または連絡先メールのためのエリアです。", ko: "파트너십, 언론, 출판 문의 또는 연락처 메일을 위한 영역입니다.", fr: "Réservez cette zone pour les partenariats, presse, demandes de publication ou courriel de contact.", de: "Reservieren Sie diesen Bereich für Partnerschaften, Presse, Veröffentlichungsanfragen oder Kontakt-E-Mail.", es: "Reserva esta área para asociaciones, prensa, consultas de publicación o correo de contacto.", ru: "Зарезервируйте эту область для партнерств, прессы, издательских запросов или контактной почты.", pt: "Reserve esta área para parcerias, imprensa, consultas de publicação ou e-mail de contato.", it: "Riserva questa area per partnership, stampa, richieste di pubblicazione o email di contatto.", nl: "Reserveer dit gebied voor partnerships, pers, publicatievragen of contact-e-mail.", pl: "Zarezerwuj to miejsce na partnerstwa, prasę, zapytania wydawnicze lub e-mail kontaktowy.", tr: "İş ortaklıkları, basın, yayınlama soruları veya iletişim e-postası için bu alanı ayırın.", vi: "Dành riêng khu vực này cho quan hệ đối tác, báo chí, thắc mắc xuất bản hoặc thư liên hệ.", id: "Cadangkan area ini untuk kemitraan, pers, pertanyaan penerbitan, atau email kontak.", uk: "Зарезервуйте цю область для партнерств, преси, видавничих запитів або контактної пошти.", el: "Δεσμεύστε αυτήν την περιοχή για συνεργασίες, τύπο, ερωτήσεις έκδοσης ή email επικοινωνίας.", cs: "Vyhradit toto místo pro partnerství, tisk, dotazy na vydávání nebo kontaktní e-mail.", sv: "Reservera detta område för partnerskap, press, publiceringsfrågor eller kontaktmail." });
raw.contactCommunityTitle = T("Community", { "zh-CN": "社区", "zh-TW": "社區", ja: "コミュニティ", ko: "커뮤니티", fr: "Communauté", de: "Community", es: "Comunidad", ru: "Сообщество", pt: "Comunidade", it: "Community", nl: "Community", pl: "Społeczność", tr: "Topluluk", vi: "Cộng đồng", id: "Komunitas", uk: "Спільнота", el: "Κοινότητα", cs: "Komunita", sv: "Gemenskap" });
raw.contactCommunityBody = T("Link out to Discord, social channels, or a future community portal when ready.", { "zh-CN": "链接至 Discord、社交频道或未来的社区门户。", "zh-TW": "連結至 Discord、社交頻道或未來的社區入口網站。", ja: "Discord、ソーシャルチャンネルまたは準備ができたら将来のコミュニティポータルへのリンクです。", ko: "Discord, 소셜 채널 또는 준비되면 미래 커뮤니티 포털로 연결합니다.", fr: "Lien vers Discord, canaux sociaux ou un futur portail communautaire quand ce sera prêt.", de: "Link zu Discord, sozialen Kanälen oder einem zukünftigen Community-Portal, wenn es bereit ist.", es: "Enlace a Discord, canales sociales o un futuro portal comunitario cuando esté listo.", ru: "Ссылка на Discord, социальные каналы или будущий портал сообщества, когда он будет готов.", pt: "Link para Discord, canais sociais ou um futuro portal comunitário quando estiver pronto.", it: "Link a Discord, canali social o un futuro portale della community quando sarà pronto.", nl: "Link naar Discord, sociale kanalen of een toekomstig community-portaal wanneer klaar.", pl: "Link do Discorda, kanałów społecznościowych lub przyszłego portalu społecznościowego, gdy będzie gotowy.", tr: "Hazır olduğunda Discord, sosyal kanallar veya gelecekteki bir topluluk portalına bağlantı.", vi: "Liên kết đến Discord, kênh xã hội hoặc cổng cộng đồng trong tương lai khi sẵn sàng.", id: "Tautan ke Discord, saluran sosial, atau portal komunitas mendatang ketika siap.", uk: "Посилання на Discord, соціальні канали або майбутній портал спільноти, коли він буде готовий.", el: "Σύνδεσμος προς Discord, κοινωνικά κανάλια ή μελλοντική πύλη κοινότητας όταν είναι έτοιμη.", cs: "Odkaz na Discord, sociální kanály nebo budoucí komunitní portál, až bude připravený.", sv: "Länk till Discord, sociala kanaler eller en framtida community-portal när den är redo." });
raw.footerPlaySteam = T("Play on Steam", { "zh-CN": "在 Steam 游玩", "zh-TW": "在 Steam 遊玩", ja: "Steam でプレイ", ko: "Steam에서 플레이", fr: "Jouer sur Steam", de: "Auf Steam spielen", es: "Jugar en Steam", ru: "Играть в Steam", pt: "Jogar no Steam", it: "Gioca su Steam", nl: "Spelen op Steam", pl: "Graj na Steam", tr: "Steam'de Oyna", vi: "Chơi trên Steam", id: "Main di Steam", uk: "Грати в Steam", el: "Παίξτε στο Steam", cs: "Hrát na Steamu", sv: "Spela på Steam" });
raw.footerViewProjects = T("View Projects", { "zh-CN": "查看项目", "zh-TW": "查看專案", ja: "プロジェクトを見る", ko: "프로젝트 보기", fr: "Voir les projets", de: "Projekte ansehen", es: "Ver proyectos", ru: "Посмотреть проекты", pt: "Ver projetos", it: "Vedi progetti", nl: "Projecten bekijken", pl: "Zobacz projekty", tr: "Projeleri Görüntüle", vi: "Xem dự án", id: "Lihat Proyek", uk: "Переглянути проекти", el: "Προβολή Έργων", cs: "Zobrazit projekty", sv: "Visa projekt" });
raw.footerContactStudio = T("Contact Studio", { "zh-CN": "联系工作室", "zh-TW": "聯繫工作室", ja: "スタジオに連絡", ko: "스튜디오 연락", fr: "Contacter le studio", de: "Studio kontaktieren", es: "Contactar al estudio", ru: "Связаться со студией", pt: "Contatar o estúdio", it: "Contatta lo studio", nl: "Studio contacteren", pl: "Skontaktuj się ze studiem", tr: "Stüdyo ile İletişime Geç", vi: "Liên hệ Studio", id: "Hubungi Studio", uk: "Зв'язатися зі студією", el: "Επικοινωνία με το Στούντιο", cs: "Kontaktovat studio", sv: "Kontakta studio" });
raw.footerColumnGames = T("Games", { "zh-CN": "游戏", "zh-TW": "遊戲", ja: "ゲーム", ko: "게임", fr: "Jeux", de: "Spiele", es: "Juegos", ru: "Игры", pt: "Jogos", it: "Giochi", nl: "Games", pl: "Gry", tr: "Oyunlar", vi: "Trò chơi", id: "Permainan", uk: "Ігри", el: "Παιχνίδια", cs: "Hry", sv: "Spel" });
raw.footerColumnDocs = T("Documents", { "zh-CN": "文档", "zh-TW": "文件", ja: "ドキュメント", ko: "문서", fr: "Documents", de: "Dokumente", es: "Documentos", ru: "Документы", pt: "Documentos", it: "Documenti", nl: "Documenten", pl: "Dokumenty", tr: "Dokümanlar", vi: "Tài liệu", id: "Dokumen", uk: "Документи", el: "Έγγραφα", cs: "Dokumenty", sv: "Dokument" });
raw.footerColumnUpdates = T("Updates", { "zh-CN": "更新", "zh-TW": "更新", ja: "更新情報", ko: "업데이트", fr: "Mises à jour", de: "Updates", es: "Actualizaciones", ru: "Обновления", pt: "Atualizações", it: "Aggiornamenti", nl: "Updates", pl: "Aktualizacje", tr: "Güncellemeler", vi: "Cập nhật", id: "Pembaruan", uk: "Оновлення", el: "Ενημερώσεις", cs: "Aktualizace", sv: "Uppdateringar" });
raw.footerColumnStudio = T("Studio", { "zh-CN": "工作室", "zh-TW": "工作室", ja: "スタジオ", ko: "스튜디오", fr: "Studio", de: "Studio", es: "Estudio", ru: "Студия", pt: "Estúdio", it: "Studio", nl: "Studio", pl: "Studio", tr: "Stüdyo", vi: "Studio", id: "Studio", uk: "Студія", el: "Στούντιο", cs: "Studio", sv: "Studio" });
raw.footerColumnSupport = T("Support", { "zh-CN": "支持", "zh-TW": "支援", ja: "サポート", ko: "지원", fr: "Support", de: "Support", es: "Soporte", ru: "Поддержка", pt: "Suporte", it: "Supporto", nl: "Ondersteuning", pl: "Wsparcie", tr: "Destek", vi: "Hỗ trợ", id: "Dukungan", uk: "Підтримка", el: "Υποστήριξη", cs: "Podpora", sv: "Support" });
raw.footerSocialGithub = T("GitHub", { "zh-CN": "GitHub", "zh-TW": "GitHub", ja: "GitHub", ko: "GitHub", fr: "GitHub", de: "GitHub", es: "GitHub", ru: "GitHub", pt: "GitHub", it: "GitHub", nl: "GitHub", pl: "GitHub", tr: "GitHub", vi: "GitHub", id: "GitHub", uk: "GitHub", el: "GitHub", cs: "GitHub", sv: "GitHub" });
raw.footerSocialSteam = T("Steam", { "zh-CN": "Steam", "zh-TW": "Steam", ja: "Steam", ko: "Steam", fr: "Steam", de: "Steam", es: "Steam", ru: "Steam", pt: "Steam", it: "Steam", nl: "Steam", pl: "Steam", tr: "Steam", vi: "Steam", id: "Steam", uk: "Steam", el: "Steam", cs: "Steam", sv: "Steam" });
raw.footerSocialContact = T("Contact", { "zh-CN": "联系", "zh-TW": "聯繫", ja: "連絡先", ko: "연락처", fr: "Contact", de: "Kontakt", es: "Contacto", ru: "Контакты", pt: "Contato", it: "Contatto", nl: "Contact", pl: "Kontakt", tr: "İletişim", vi: "Liên hệ", id: "Kontak", uk: "Контакти", el: "Επικοινωνία", cs: "Kontakt", sv: "Kontakt" });
raw.footerCopyright = T("© 2026 Hanazar Games. All rights reserved.", { "zh-CN": "© 2026 哈纳扎尔工作室。保留所有权利。", "zh-TW": "© 2026 哈納扎爾工作室。保留所有權利。", ja: "© 2026 Hanazar Games. All rights reserved.", ko: "© 2026 Hanazar Games. All rights reserved.", fr: "© 2026 Hanazar Games. Tous droits réservés.", de: "© 2026 Hanazar Games. Alle Rechte vorbehalten.", es: "© 2026 Hanazar Games. Todos los derechos reservados.", ru: "© 2026 Hanazar Games. Все права защищены.", pt: "© 2026 Hanazar Games. Todos os direitos reservados.", it: "© 2026 Hanazar Games. Tutti i diritti riservati.", nl: "© 2026 Hanazar Games. Alle rechten voorbehouden.", pl: "© 2026 Hanazar Games. Wszelkie prawa zastrzeżone.", tr: "© 2026 Hanazar Games. Tüm hakları saklıdır.", vi: "© 2026 Hanazar Games. Mọi quyền được bảo lưu.", id: "© 2026 Hanazar Games. Hak cipta dilindungi.", uk: "© 2026 Hanazar Games. Всі права захищені.", el: "© 2026 Hanazar Games. Με επιφύλαξη παντός δικαιώματος.", cs: "© 2026 Hanazar Games. Všechna práva vyhrazena.", sv: "© 2026 Hanazar Games. Alla rättigheter förbehållna." });
raw.footerPrivacy = T("Privacy Policy", { "zh-CN": "隐私政策", "zh-TW": "隱私政策", ja: "プライバシーポリシー", ko: "개인정보 처리방침", fr: "Politique de confidentialité", de: "Datenschutz", es: "Política de privacidad", ru: "Политика конфиденциальности", pt: "Política de privacidade", it: "Informativa sulla privacy", nl: "Privacybeleid", pl: "Polityka prywatności", tr: "Gizlilik Politikası", vi: "Chính sách bảo mật", id: "Kebijakan Privasi", uk: "Політика конфіденційності", el: "Πολιτική Απορρήτου", cs: "Zásady ochrany osobních údajů", sv: "Integritetspolicy" });
raw.footerTerms = T("Terms", { "zh-CN": "条款", "zh-TW": "條款", ja: "利用規約", ko: "이용 약관", fr: "Conditions", de: "Nutzungsbedingungen", es: "Términos", ru: "Условия", pt: "Termos", it: "Termini", nl: "Voorwaarden", pl: "Warunki", tr: "Koşullar", vi: "Điều khoản", id: "Ketentuan", uk: "Умови", el: "Όροι", cs: "Podmínky", sv: "Villkor" });
raw.footerLinks = T("Links", { "zh-CN": "链接", "zh-TW": "連結", ja: "リンク", ko: "링크", fr: "Liens", de: "Links", es: "Enlaces", ru: "Ссылки", pt: "Links", it: "Link", nl: "Links", pl: "Linki", tr: "Bağlantılar", vi: "Liên kết", id: "Tautan", uk: "Посилання", el: "Σύνδεσμοι", cs: "Odkazy", sv: "Länkar" });

raw.gamesHeroEyebrow = T("Hanazar Games", { "zh-CN": "哈纳扎尔工作室", "zh-TW": "哈納扎爾工作室", ja: "Hanazar Games", ko: "Hanazar Games", fr: "Hanazar Games", de: "Hanazar Games", es: "Hanazar Games", ru: "Hanazar Games", pt: "Hanazar Games" });
raw.gamesHeroTitle = T("Games Hub", { "zh-CN": "游戏合集", "zh-TW": "遊戲合集", ja: "ゲームハブ", ko: "게임 허브", fr: "Hub de jeux", de: "Spiele-Hub", es: "Hub de juegos", ru: "Игровой хаб", pt: "Hub de jogos" });
raw.gamesHeroSubtitle = T("A growing collection of browser-based games built by Hanazar Games. No install needed — click and play.", { "zh-CN": "由哈纳扎尔工作室打造的浏览器游戏合集。无需安装 — 点击即玩。", "zh-TW": "由哈納扎爾工作室打造的瀏覽器遊戲合集。無需安裝 — 點擊即玩。", ja: "Hanazar Games が構築したブラウザベースのゲーム集。インストール不要 — クリックしてプレイ。", ko: "Hanazar Games가 만든 브라우저 기반 게임 모음입니다. 설치 불필요 — 클릭하고 플레이하세요.", fr: "Une collection croissante de jeux basés sur navigateur construite par Hanazar Games. Pas d'installation nécessaire — cliquez et jouez.", de: "Eine wachsende Sammlung browserbasierter Spiele von Hanazar Games. Keine Installation nötig — klicken und spielen.", es: "Una colección creciente de juegos basados en navegador construidos por Hanazar Games. Sin instalación — haz clic y juega.", ru: "Растущая коллекция браузерных игр от Hanazar Games. Установка не требуется — нажми и играй.", pt: "Uma coleção crescente de jogos baseados em navegador construídos pela Hanazar Games. Sem instalação — clique e jogue." });
raw.gameTicTacToeTitle = T("Tic-Tac-Toe", { "zh-CN": "井字棋", "zh-TW": "井字棋", ja: "Tic-Tac-Toe", ko: "Tic-Tac-Toe", fr: "Tic-Tac-Toe", de: "Tic-Tac-Toe", es: "Tic-Tac-Toe", ru: "Крестики-нолики", pt: "Jogo da Velha" });
raw.gameTicTacToeDesc = T("Classic tic-tac-toe with a modern twist — includes Connect Four, Gomoku, custom boards, AI opponents, puzzle rush, tactics trainer, and full replay analysis.", { "zh-CN": "经典井字棋现代升级版 — 包含四连棋、五子棋、自定义棋盘、AI对手、速通挑战、战术训练与完整复盘分析。", "zh-TW": "經典井字棋現代升級版 — 包含四連棋、五子棋、自訂棋盤、AI對手、速通挑戰、戰術訓練與完整覆盤分析。", ja: "モダンな twist を加えたクラシック tic-tac-toe — 四目並べ、五目並べ、カスタムボード、AI対戦、パズルラッシュ、戦術トレーナー、完全なリプレイ分析を含む。", ko: "현대적인 변화를 더한 클래식 틱택토 — 사목, 오목, 사용자 정의 보드, AI 상대, 퍼즐 러시, 전술 트레이너 및 전체 리플레이 분석 포함.", fr: "Tic-tac-toe classique avec une touche moderne — inclut Puissance 4, Gomoku, plateaux personnalisés, adversaires IA, puzzle rush, entraîneur tactique et analyse complète des replays.", de: "Klassisches Tic-Tac-Toe mit modernem Twist — enthält Vier gewinnt, Gomoku, benutzerdefinierte Bretter, AI-Gegner, Puzzle-Rush, Taktik-Trainer und vollständige Replay-Analyse.", es: "Tic-tac-toe clásico con un giro moderno — incluye Conecta 4, Gomoku, tableros personalizados, oponentes de IA, puzzle rush, entrenador táctico y análisis completo de repeticiones.", ru: "Классические крестики-нолики с современным поворотом — включает четыре в ряд, гомоку, пользовательские доски, ИИ-противников, пазл-раш, тактический тренер и полный анализ повторов.", pt: "Jogo da velha clássico com um toque moderno — inclui Ligue 4, Gomoku, tabuleiros personalizados, oponentes de IA, puzzle rush, treinador tático e análise completa de replays." });
raw.gameMinesweeperTitle = T("Minesweeper", { "zh-CN": "扫雷", "zh-TW": "踩地雷", ja: "マインスイーパー", ko: "지뢰찾기", fr: "Démineur", de: "Minesweeper", es: "Buscaminas", ru: "Сапер", pt: "Campo Minado" });
raw.gameMinesweeperDesc = T("The timeless mine-clearing puzzle. Use logic and intuition to flag every mine without setting one off.", { "zh-CN": "永恒的扫雷解谜游戏。运用逻辑与直觉标记所有地雷，不要触发它们。", "zh-TW": "永恆的踩地雷解謎遊戲。運用邏輯與直覺標記所有地雷，不要觸發它們。", ja: "永遠のマイン除去パズル。論理と直感を使って、すべての地雷に旗を立てて爆発させないようにしましょう。", ko: "영원한 지뢰 제거 퍼즐입니다. 논리와 직관을 사용하여 모든 지뢰에 깃발을 꽂고 폭발시키지 마세요.", fr: "Le puzzle intemporel de déminage. Utilisez la logique et l'intuition pour signaler chaque mine sans en déclencher une.", de: "Das zeitlose Minenräum-Puzzle. Verwenden Sie Logik und Intuition, um jede Mine zu markieren, ohne eine auszulösen.", es: "El puzzle atemporal de desminado. Usa la lógica y la intuición para marcar cada mina sin detonar una.", ru: "Вневременная головоломка сапера. Используйте логику и интуицию, чтобы отметить каждую мину, не подорвав ее.", pt: "O puzzle atemporal de desativação de minas. Use lógica e intuição para marcar cada mina sem detonar uma." });
raw.game2048Title = T("3D 2048", { "zh-CN": "3D 2048", "zh-TW": "3D 2048", ja: "3D 2048", ko: "3D 2048", fr: "2048 3D", de: "3D 2048", es: "2048 3D", ru: "3D 2048", pt: "2048 3D" });
raw.game2048Desc = T("The classic number-merging game reimagined in three dimensions. Slide blocks in 3D space and reach 2048.", { "zh-CN": "经典数字合并游戏的三维重制版。在立体空间中滑动方块，合成2048。", "zh-TW": "經典數字合併遊戲的三維重製版。在立體空間中滑動方塊，合成2048。", ja: "3次元に再構想されたクラシックな数字合成ゲーム。立体空間でブロックをスライドさせて2048を目指しましょう。", ko: "3차원으로 재구상된 클래식 숫자 병합 게임입니다. 입체 공간에서 블록을 슬라이드하여 2048을 만드세요.", fr: "Le jeu classique de fusion de nombres réimaginé en trois dimensions. Faites glisser les blocs dans l'espace 3D et atteignez 2048.", de: "Das klassische Zahlen-Verschmelzungsspiel in drei Dimensionen neu erdacht. Schieben Sie Blöcke im 3D-Raum und erreichen Sie 2048.", es: "El clásico juego de fusión de números reimaginado en tres dimensiones. Desliza bloques en el espacio 3D y alcanza 2048.", ru: "Классическая игра слияния чисел, переосмысленная в трех измерениях. Сдвигайте блоки в 3D-пространстве и достигните 2048.", pt: "O clássico jogo de fusão de números reimaginado em três dimensões. Deslize blocos no espaço 3D e alcance 2048." });
raw.gameTagStrategy = T("Strategy", { "zh-CN": "策略", "zh-TW": "策略", ja: "戦略", ko: "전략", fr: "Stratégie", de: "Strategie", es: "Estrategia", ru: "Стратегия", pt: "Estratégia" });
raw.gameTagPuzzle = T("Puzzle", { "zh-CN": "解谜", "zh-TW": "解謎", ja: "パズル", ko: "퍼즐", fr: "Puzzle", de: "Puzzle", es: "Puzzle", ru: "Головоломка", pt: "Quebra-cabeça" });
raw.gameTagArcade = T("Arcade", { "zh-CN": "街机", "zh-TW": "街機", ja: "アーケード", ko: "아케이드", fr: "Arcade", de: "Arcade", es: "Arcade", ru: "Аркада", pt: "Arcade" });
raw.gamePlayButton = T("Play Game", { "zh-CN": "开始游戏", "zh-TW": "開始遊戲", ja: "プレイ", ko: "게임 플레이", fr: "Jouer", de: "Spielen", es: "Jugar", ru: "Играть", pt: "Jogar" });
raw.gamesMoreSoon = T("More games coming soon.", { "zh-CN": "更多游戏即将推出。", "zh-TW": "更多遊戲即將推出。", ja: "さらにゲームが近日公開予定。", ko: "더 많은 게임이 곧 출시됩니다.", fr: "Plus de jeux à venir bientôt.", de: "Weitere Spiele folgen bald.", es: "Más juegos próximamente.", ru: "Скоро выйдет больше игр.", pt: "Mais jogos em breve." });
raw.gamesBackHome = T("← Back to Home", { "zh-CN": "← 返回首页", "zh-TW": "← 返回首頁", ja: "← ホームに戻る", ko: "← 홈으로 돌아가기", fr: "← Retour à l'accueil", de: "← Zurück zur Startseite", es: "← Volver al inicio", ru: "← На главную", pt: "← Voltar ao início" });
raw.settingsTitle = T("Project Settings", { "zh-CN": "项目设置", "zh-TW": "專案設定", ja: "プロジェクト設定", ko: "프로젝트 설정", fr: "Paramètres du projet", de: "Projekteinstellungen", es: "Configuración del proyecto", ru: "Настройки проекта", pt: "Configurações do projeto" });
raw.settingsClose = T("Close settings", { "zh-CN": "关闭设置", "zh-TW": "關閉設定", ja: "設定を閉じる", ko: "설정 닫기", fr: "Fermer les paramètres", de: "Einstellungen schließen", es: "Cerrar configuración", ru: "Закрыть настройки", pt: "Fechar configurações" });
raw.tabStyle = T("Style", { "zh-CN": "样式", "zh-TW": "樣式", ja: "スタイル", ko: "스타일", fr: "Style", de: "Stil", es: "Estilo", ru: "Стиль", pt: "Estilo" });
raw.tabLanguage = T("Language", { "zh-CN": "语言", "zh-TW": "語言", ja: "言語", ko: "언어", fr: "Langue", de: "Sprache", es: "Idioma", ru: "Язык", pt: "Idioma" });
raw.tabAudio = T("Audio", { "zh-CN": "音频", "zh-TW": "音訊", ja: "オーディオ", ko: "오디오", fr: "Audio", de: "Audio", es: "Audio", ru: "Аудио", pt: "Áudio" });
raw.tabAnimation = T("Animation", { "zh-CN": "动画", "zh-TW": "動畫", ja: "アニメーション", ko: "애니메이션", fr: "Animation", de: "Animation", es: "Animación", ru: "Анимация", pt: "Animação" });
raw.tabPerformance = T("Performance", { "zh-CN": "性能", "zh-TW": "效能", ja: "パフォーマンス", ko: "성능", fr: "Performance", de: "Leistung", es: "Rendimiento", ru: "Производительность", pt: "Desempenho" });
raw.tabApi = T("API", { "zh-CN": "接口", "zh-TW": "介面", ja: "API", ko: "API", fr: "API", de: "API", es: "API", ru: "API", pt: "API" });
raw.tabShortcuts = T("Shortcuts", { "zh-CN": "快捷键", "zh-TW": "快捷鍵", ja: "ショートカット", ko: "단축키", fr: "Raccourcis", de: "Tastenkürzel", es: "Atajos", ru: "Горячие клавиши", pt: "Atalhos" });
raw.tabOther = T("Other", { "zh-CN": "其他", "zh-TW": "其他", ja: "その他", ko: "기타", fr: "Autre", de: "Sonstiges", es: "Otros", ru: "Другое", pt: "Outros" });
raw.tabAnnouncement = T("Announce", { "zh-CN": "公告", "zh-TW": "公告", ja: "お知らせ", ko: "공지", fr: "Annonces", de: "Ankündigungen", es: "Anuncios", ru: "Объявления", pt: "Anúncios" });
raw.tabAbout = T("About", { "zh-CN": "关于", "zh-TW": "關於", ja: "概要", ko: "소개", fr: "À propos", de: "Über", es: "Acerca de", ru: "О нас", pt: "Sobre" });
raw.stTheme = T("Theme", { "zh-CN": "主题", "zh-TW": "主題", ja: "テーマ", ko: "테마", fr: "Thème", de: "Thema", es: "Tema", ru: "Тема", pt: "Tema" });
raw.stFont = T("Font", { "zh-CN": "字体", "zh-TW": "字體", ja: "フォント", ko: "폰트", fr: "Police", de: "Schriftart", es: "Fuente", ru: "Шрифт", pt: "Fonte" });
raw.stColorPreset = T("Color Preset", { "zh-CN": "配色预设", "zh-TW": "配色預設", ja: "カラープリセット", ko: "색상 프리셋", fr: "Préréglage de couleur", de: "Farbvoreinstellung", es: "Preajuste de color", ru: "Цветовая схема", pt: "Predefinição de cor" });
raw.stContrast = T("Contrast", { "zh-CN": "对比度", "zh-TW": "對比度", ja: "コントラスト", ko: "대비", fr: "Contraste", de: "Kontrast", es: "Contraste", ru: "Контраст", pt: "Contraste" });
raw.stInterfaceLang = T("Interface Language", { "zh-CN": "界面语言", "zh-TW": "介面語言", ja: "インターフェース言語", ko: "인터페이스 언어", fr: "Langue de l'interface", de: "Oberflächensprache", es: "Idioma de interfaz", ru: "Язык интерфейса", pt: "Idioma da interface" });
raw.stLangDesc = T("Select your preferred display language. Content language is not affected.", { "zh-CN": "选择你的首选显示语言。内容语言不受影响。", "zh-TW": "選擇你的首選顯示語言。內容語言不受影響。", ja: "優先する表示言語を選択してください。コンテンツの言語には影響しません。", ko: "선호하는 표시 언어를 선택하세요. 콘텐츠 언어에는 영향을 주지 않습니다.", fr: "Sélectionnez votre langue d'affichage préférée. La langue du contenu n'est pas affectée.", de: "Wählen Sie Ihre bevorzugte Anzeigesprache. Die Inhaltssprache wird nicht beeinflusst.", es: "Selecciona tu idioma de visualización preferido. El idioma del contenido no se ve afectado.", ru: "Выберите предпочитаемый язык отображения. Язык контента не изменится.", pt: "Selecione seu idioma de exibição preferido. O idioma do conteúdo não é afetado." });
raw.stMasterVolume = T("Master Volume", { "zh-CN": "主音量", "zh-TW": "主音量", ja: "マスター音量", ko: "마스터 볼륨", fr: "Volume principal", de: "Hauptlautstärke", es: "Volumen maestro", ru: "Общая громкость", pt: "Volume principal" });
raw.stSfx = T("Sound Effects", { "zh-CN": "音效", "zh-TW": "音效", ja: "効果音", ko: "효과음", fr: "Effets sonores", de: "Soundeffekte", es: "Efectos de sonido", ru: "Звуковые эффекты", pt: "Efeitos sonoros" });
raw.stSfxVolume = T("SFX Volume", { "zh-CN": "音效音量", "zh-TW": "音效音量", ja: "効果音の音量", ko: "효과음 볼륨", fr: "Volume des effets", de: "SFX-Lautstärke", es: "Volumen de efectos", ru: "Громкость эффектов", pt: "Volume de efeitos" });
raw.stSfxStyle = T("SFX Style", { "zh-CN": "音效风格", "zh-TW": "音效風格", ja: "効果音のスタイル", ko: "효과음 스타일", fr: "Style des effets", de: "SFX-Stil", es: "Estilo de efectos", ru: "Стиль эффектов", pt: "Estilo de efeitos" });
raw.stBgm = T("Background Music", { "zh-CN": "背景音乐", "zh-TW": "背景音樂", ja: "BGM", ko: "배경 음악", fr: "Musique de fond", de: "Hintergrundmusik", es: "Música de fondo", ru: "Фоновая музыка", pt: "Música de fundo" });
raw.stBgmVolume = T("BGM Volume", { "zh-CN": "音乐音量", "zh-TW": "音樂音量", ja: "BGM の音量", ko: "BGM 볼륨", fr: "Volume de la musique", de: "Musiklautstärke", es: "Volumen de música", ru: "Громкость музыки", pt: "Volume da música" });
raw.stBgmStyle = T("Music Style", { "zh-CN": "音乐风格", "zh-TW": "音樂風格", ja: "音楽のスタイル", ko: "음악 스타일", fr: "Style musical", de: "Musikstil", es: "Estilo musical", ru: "Музыкальный стиль", pt: "Estilo musical" });
raw.stBgmNote = T("Top 12 curated styles. Full list available via import.", { "zh-CN": "精选12种风格。完整列表可通过导入获取。", "zh-TW": "精選12種風格。完整列表可透過匯入取得。", ja: "厳選された12スタイル。完全なリストはインポートで利用可能。", ko: "엄선된 12가지 스타일. 전체 목록은 가져오기로 이용 가능합니다.", fr: "12 styles sélectionnés. La liste complète est disponible via importation.", de: "Top 12 kuratierte Stile. Vollständige Liste über Import verfügbar.", es: "Top 12 estilos curados. Lista completa disponible vía importación.", ru: "Топ-12 отобранных стилей. Полный список доступен через импорт.", pt: "Top 12 estilos selecionados. Lista completa disponível via importação." });
raw.stEnableAnim = T("Enable Animations", { "zh-CN": "启用动画", "zh-TW": "啟用動畫", ja: "アニメーションを有効にする", ko: "애니메이션 활성화", fr: "Activer les animations", de: "Animationen aktivieren", es: "Habilitar animaciones", ru: "Включить анимации", pt: "Ativar animações" });
raw.stAnimSpeed = T("Animation Speed", { "zh-CN": "动画速度", "zh-TW": "動畫速度", ja: "アニメーション速度", ko: "애니메이션 속도", fr: "Vitesse d'animation", de: "Animationsgeschwindigkeit", es: "Velocidad de animación", ru: "Скорость анимации", pt: "Velocidade da animação" });
raw.stAnimSpeedDesc = T("Lower value means slower animations.", { "zh-CN": "数值越低动画越慢。", "zh-TW": "數值越低動畫越慢。", ja: "値が低いほどアニメーションは遅くなります。", ko: "값이 낮을수록 애니메이션이 느려집니다.", fr: "Une valeur plus basse signifie des animations plus lentes.", de: "Niedrigerer Wert bedeutet langsamere Animationen.", es: "Un valor más bajo significa animaciones más lentas.", ru: "Меньшее значение означает более медленную анимацию.", pt: "Um valor mais baixo significa animações mais lentas." });
raw.stIndivEffects = T("Individual Effects", { "zh-CN": "独立效果", "zh-TW": "獨立效果", ja: "個別の効果", ko: "개별 효과", fr: "Effets individuels", de: "Individuelle Effekte", es: "Efectos individuales", ru: "Отдельные эффекты", pt: "Efeitos individuais" });
raw.stUiFade = T("UI Fade In", { "zh-CN": "界面渐显", "zh-TW": "介面漸顯", ja: "UI フェードイン", ko: "UI 페이드 인", fr: "Fondu UI", de: "UI-Einblendung", es: "Desvanecimiento UI", ru: "Плавное появление UI", pt: "Desvanecimento UI" });
raw.stBtnHover = T("Button Hover", { "zh-CN": "按钮悬停", "zh-TW": "按鈕懸停", ja: "ボタンホバー", ko: "버튼 호버", fr: "Survol des boutons", de: "Button-Hover", es: "Hover de botón", ru: "Наведение на кнопку", pt: "Hover de botão" });
raw.stModalTrans = T("Modal Transition", { "zh-CN": "弹窗过渡", "zh-TW": "彈窗過渡", ja: "モーダル遷移", ko: "모달 전환", fr: "Transition modale", de: "Modal-Übergang", es: "Transición de modal", ru: "Переход модального окна", pt: "Transição de modal" });
raw.stReduceAnim = T("Reduce Animations", { "zh-CN": "减少动画", "zh-TW": "減少動畫", ja: "アニメーションを減らす", ko: "애니메이션 줄이기", fr: "Réduire les animations", de: "Animationen reduzieren", es: "Reducir animaciones", ru: "Уменьшить анимации", pt: "Reduzir animações" });
raw.stDisableBlur = T("Disable Glassmorphism Blur", { "zh-CN": "禁用毛玻璃模糊", "zh-TW": "禁用毛玻璃模糊", ja: "グラスモーフィズムのぼかしを無効にする", ko: "글래스모피즘 블러 비활성화", fr: "Désactiver le flou glassmorphism", de: "Glassmorphism-Weichzeichnung deaktivieren", es: "Deshabilitar desenfoque glassmorphism", ru: "Отключить размытие glassmorphism", pt: "Desativar desfoque glassmorphism" });
raw.stLowRes = T("Low Resolution Preview", { "zh-CN": "低分辨率预览", "zh-TW": "低解析度預覽", ja: "低解像度プレビュー", ko: "저해상도 미리보기", fr: "Aperçu basse résolution", de: "Niedrigauflösungsvorschau", es: "Vista previa de baja resolución", ru: "Предпросмотр низкого разрешения", pt: "Pré-visualização de baixa resolução" });
raw.stLazyLoad = T("Lazy Load Modules", { "zh-CN": "延迟加载模块", "zh-TW": "延遲載入模組", ja: "モジュールの遅延読み込み", ko: "모듈 지연 로드", fr: "Chargement différé des modules", de: "Module verzögert laden", es: "Carga diferida de módulos", ru: "Отложенная загрузка модулей", pt: "Carregamento lento de módulos" });
raw.stDisableParticles = T("Disable Particle Effects", { "zh-CN": "禁用粒子效果", "zh-TW": "禁用粒子效果", ja: "パーティクル効果を無効にする", ko: "파티클 효과 비활성화", fr: "Désactiver les effets de particules", de: "Partikeleffekte deaktivieren", es: "Deshabilitar efectos de partículas", ru: "Отключить эффекты частиц", pt: "Desativar efeitos de partículas" });
raw.stAggressiveCache = T("Aggressive Cache Strategy", { "zh-CN": "激进缓存策略", "zh-TW": "激進快取策略", ja: "アグレッシブキャッシュ戦略", ko: "공격적 캐시 전략", fr: "Stratégie de cache agressive", de: "Aggressive Cache-Strategie", es: "Estrategia de caché agresiva", ru: "Агрессивная стратегия кэширования", pt: "Estratégia de cache agressiva" });
raw.stDevMode = T("Developer Debug Mode", { "zh-CN": "开发者调试模式", "zh-TW": "開發者偵錯模式", ja: "開発者デバッグモード", ko: "개발자 디버그 모드", fr: "Mode débogage développeur", de: "Entwickler-Debug-Modus", es: "Modo de depuración de desarrollador", ru: "Режим отладки разработчика", pt: "Modo de depuração de desenvolvedor" });
raw.stMaxConcurrent = T("Max Concurrent Requests", { "zh-CN": "最大并发请求", "zh-TW": "最大併發請求", ja: "最大同時リクエスト数", ko: "최대 동시 요청", fr: "Requêtes simultanées max", de: "Max. gleichzeitige Anfragen", es: "Solicitudes concurrentes máximas", ru: "Макс. одновременных запросов", pt: "Requisições simultâneas máximas" });
raw.stPerfDesc = T("Disabling visual effects improves performance on low-end devices.", { "zh-CN": "关闭部分视觉效果可提升低配设备的流畅度。", "zh-TW": "關閉部分視覺效果可提升低效能裝置的流暢度。", ja: "視覚効果を一部無効にすると、低スペックデバイスの動作が改善されます。", ko: "시각 효과를 일부 비활성화하면 저사양 기기의 성능이 향상됩니다.", fr: "La désactivation de certains effets visuels améliore les performances sur les appareils bas de gamme.", de: "Das Deaktivieren einiger visueller Effekte verbessert die Leistung auf leistungsschwachen Geräten.", es: "Deshabilitar algunos efectos visuales mejora el rendimiento en dispositivos de gama baja.", ru: "Отключение некоторых визуальных эффектов улучшает производительность на слабых устройствах.", pt: "Desativar alguns efeitos visuais melhora o desempenho em dispositivos de baixo custo." });
raw.stApiUrl = T("API Base URL", { "zh-CN": "API 基础地址", "zh-TW": "API 基礎位址", ja: "API ベース URL", ko: "API 기본 URL", fr: "URL de base API", de: "API-Basis-URL", es: "URL base de API", ru: "Базовый URL API", pt: "URL base da API" });
raw.stApiTimeout = T("Timeout (ms)", { "zh-CN": "超时 (毫秒)", "zh-TW": "逾時 (毫秒)", ja: "タイムアウト (ms)", ko: "타임아웃 (ms)", fr: "Délai d'attente (ms)", de: "Timeout (ms)", es: "Tiempo de espera (ms)", ru: "Таймаут (мс)", pt: "Tempo limite (ms)" });
raw.stApiRetries = T("Retry Count", { "zh-CN": "重试次数", "zh-TW": "重試次數", ja: "再試行回数", ko: "재시도 횟수", fr: "Nombre de tentatives", de: "Wiederholungsversuche", es: "Conteo de reintentos", ru: "Количество повторов", pt: "Contagem de tentativas" });
raw.stShortcuts = T("Keyboard Shortcuts", { "zh-CN": "键盘快捷键", "zh-TW": "鍵盤快捷鍵", ja: "キーボードショートカット", ko: "키보드 단축키", fr: "Raccourcis clavier", de: "Tastenkürzel", es: "Atajos de teclado", ru: "Горячие клавиши", pt: "Atalhos de teclado" });
raw.stShortcutsDesc = T("These shortcuts are available across the site.", { "zh-CN": "这些快捷键在整个网站中可用。", "zh-TW": "這些快捷鍵在整個網站中可用。", ja: "これらのショートカットはサイト全体で使用できます。", ko: "이러한 단축키는 사이트 전체에서 사용할 수 있습니다.", fr: "Ces raccourcis sont disponibles sur tout le site.", de: "Diese Tastenkürzel sind auf der gesamten Website verfügbar.", es: "Estos atajos están disponibles en todo el sitio.", ru: "Эти горячие клавиши доступны на всем сайте.", pt: "Esses atalhos estão disponíveis em todo o site." });
raw.scOpenSettings = T("Open Settings", { "zh-CN": "打开设置", "zh-TW": "開啟設定", ja: "設定を開く", ko: "설정 열기", fr: "Ouvrir les paramètres", de: "Einstellungen öffnen", es: "Abrir configuración", ru: "Открыть настройки", pt: "Abrir configurações" });
raw.scCloseModal = T("Close Modal", { "zh-CN": "关闭弹窗", "zh-TW": "關閉彈窗", ja: "モーダルを閉じる", ko: "모달 닫기", fr: "Fermer la modale", de: "Modal schließen", es: "Cerrar modal", ru: "Закрыть модальное окно", pt: "Fechar modal" });
raw.scNavigateTabs = T("Navigate Tabs", { "zh-CN": "切换标签页", "zh-TW": "切換標籤頁", ja: "タブを切り替える", ko: "탭 탐색", fr: "Naviguer les onglets", de: "Tabs navigieren", es: "Navegar pestañas", ru: "Переключать вкладки", pt: "Navegar abas" });
raw.scToggleTheme = T("Toggle Theme", { "zh-CN": "切换主题", "zh-TW": "切換主題", ja: "テーマを切り替える", ko: "테마 전환", fr: "Basculer le thème", de: "Thema wechseln", es: "Alternar tema", ru: "Переключить тему", pt: "Alternar tema" });
raw.scMute = T("Mute / Unmute", { "zh-CN": "静音 / 取消静音", "zh-TW": "靜音 / 取消靜音", ja: "ミュート / 解除", ko: "음소거 / 해제", fr: "Muet / Réactiver", de: "Stummschalten / Aufheben", es: "Silenciar / Activar", ru: "Без звука / Включить", pt: "Silenciar / Ativar" });
raw.scReset = T("Reset Settings", { "zh-CN": "重置设置", "zh-TW": "重置設定", ja: "設定をリセット", ko: "설정 초기화", fr: "Réinitialiser les paramètres", de: "Einstellungen zurücksetzen", es: "Restablecer configuración", ru: "Сбросить настройки", pt: "Redefinir configurações" });
raw.scExport = T("Export Config", { "zh-CN": "导出配置", "zh-TW": "匯出配置", ja: "設定をエクスポート", ko: "설정 내보내기", fr: "Exporter la config", de: "Konfiguration exportieren", es: "Exportar config", ru: "Экспортировать конфиг", pt: "Exportar config" });
raw.scImport = T("Import Config", { "zh-CN": "导入配置", "zh-TW": "匯入配置", ja: "設定をインポート", ko: "설정 가져오기", fr: "Importer la config", de: "Konfiguration importieren", es: "Importar config", ru: "Импортировать конфиг", pt: "Importar config" });
raw.stReset = T("Reset", { "zh-CN": "重置", "zh-TW": "重置", ja: "リセット", ko: "초기화", fr: "Réinitialiser", de: "Zurücksetzen", es: "Restablecer", ru: "Сброс", pt: "Redefinir" });
raw.stResetDesc = T("Restore all settings to their default values. This cannot be undone.", { "zh-CN": "将所有设置恢复为默认值。此操作不可撤销。", "zh-TW": "將所有設定恢復為預設值。此操作不可撤銷。", ja: "すべての設定をデフォルト値に戻します。この操作は元に戻せません。", ko: "모든 설정을 기본값으로 되돌립니다. 이 작업은 되돌릴 수 없습니다.", fr: "Restaurez tous les paramètres à leurs valeurs par défaut. Cette action ne peut pas être annulée.", de: "Stellen Sie alle Einstellungen auf die Standardwerte zurück. Dies kann nicht rückgängig gemacht werden.", es: "Restaura todos los ajustes a sus valores predeterminados. Esta acción no se puede deshacer.", ru: "Восстановить все настройки до значений по умолчанию. Это действие нельзя отменить.", pt: "Restaurar todas as configurações para os valores padrão. Esta ação não pode ser desfeita." });
raw.stResetBtn = T("Reset All Settings", { "zh-CN": "重置所有设置", "zh-TW": "重置所有設定", ja: "すべての設定をリセット", ko: "모든 설정 초기화", fr: "Réinitialiser tous les paramètres", de: "Alle Einstellungen zurücksetzen", es: "Restablecer todos los ajustes", ru: "Сбросить все настройки", pt: "Redefinir todas as configurações" });
raw.stExportImport = T("Export / Import", { "zh-CN": "导出 / 导入", "zh-TW": "匯出 / 匯入", ja: "エクスポート / インポート", ko: "내보내기 / 가져오기", fr: "Exporter / Importer", de: "Exportieren / Importieren", es: "Exportar / Importar", ru: "Экспорт / Импорт", pt: "Exportar / Importar" });
raw.stCopyJson = T("Copy JSON", { "zh-CN": "复制 JSON", "zh-TW": "複製 JSON", ja: "JSON をコピー", ko: "JSON 복사", fr: "Copier le JSON", de: "JSON kopieren", es: "Copiar JSON", ru: "Копировать JSON", pt: "Copiar JSON" });
raw.stDownloadJson = T("Download JSON", { "zh-CN": "下载 JSON", "zh-TW": "下載 JSON", ja: "JSON をダウンロード", ko: "JSON 다운로드", fr: "Télécharger le JSON", de: "JSON herunterladen", es: "Descargar JSON", ru: "Скачать JSON", pt: "Baixar JSON" });
raw.stImportJson = T("Import JSON", { "zh-CN": "导入 JSON", "zh-TW": "匯入 JSON", ja: "JSON をインポート", ko: "JSON 가져오기", fr: "Importer le JSON", de: "JSON importieren", es: "Importar JSON", ru: "Импортировать JSON", pt: "Importar JSON" });
raw.stCancel = T("Cancel", { "zh-CN": "取消", "zh-TW": "取消", ja: "キャンセル", ko: "취소", fr: "Annuler", de: "Abbrechen", es: "Cancelar", ru: "Отмена", pt: "Cancelar" });
raw.stConfirmImport = T("Confirm Import", { "zh-CN": "确认导入", "zh-TW": "確認匯入", ja: "インポートを確認", ko: "가져오기 확인", fr: "Confirmer l'importation", de: "Import bestätigen", es: "Confirmar importación", ru: "Подтвердить импорт", pt: "Confirmar importação" });
raw.stImportPlaceholder = T("Paste your settings JSON here...", { "zh-CN": "在此粘贴你的设置 JSON...", "zh-TW": "在此貼上你的設定 JSON...", ja: "設定 JSON をここに貼り付けてください...", ko: "설정 JSON을 여기에 붙여넣으세요...", fr: "Collez votre JSON de paramètres ici...", de: "Fügen Sie Ihre Einstellungen-JSON hier ein...", es: "Pega tu JSON de configuración aquí...", ru: "Вставьте JSON настроек здесь...", pt: "Cole seu JSON de configurações aqui..." });
raw.stCache = T("Cache", { "zh-CN": "缓存", "zh-TW": "快取", ja: "キャッシュ", ko: "캐시", fr: "Cache", de: "Cache", es: "Caché", ru: "Кэш", pt: "Cache" });
raw.stCacheDesc = T("Clear all locally stored data including settings.", { "zh-CN": "清除所有本地存储的数据，包括设置。", "zh-TW": "清除所有本地儲存的資料，包括設定。", ja: "設定を含む、ローカルに保存されたすべてのデータを削除します。", ko: "설정을 포함하여 로컬에 저장된 모든 데이터를 지웁니다.", fr: "Effacez toutes les données stockées localement, y compris les paramètres.", de: "Löschen Sie alle lokal gespeicherten Daten einschließlich Einstellungen.", es: "Limpia todos los datos almacenados localmente, incluida la configuración.", ru: "Очистить все локально сохраненные данные, включая настройки.", pt: "Limpe todos os dados armazenados localmente, incluindo configurações." });
raw.stClearCache = T("Clear Local Cache", { "zh-CN": "清除本地缓存", "zh-TW": "清除本地快取", ja: "ローカルキャッシュを削除", ko: "로컬 캐시 지우기", fr: "Effacer le cache local", de: "Lokalen Cache löschen", es: "Limpiar caché local", ru: "Очистить локальный кэш", pt: "Limpar cache local" });
raw.stImported = T("Settings imported successfully.", { "zh-CN": "设置导入成功。", "zh-TW": "設定匯入成功。", ja: "設定のインポートに成功しました。", ko: "설정 가져오기 성공.", fr: "Paramètres importés avec succès.", de: "Einstellungen erfolgreich importiert.", es: "Configuración importada exitosamente.", ru: "Настройки успешно импортированы.", pt: "Configurações importadas com sucesso." });
raw.stImportFail = T("Invalid JSON. Please check your config.", { "zh-CN": "JSON 格式无效。请检查你的配置。", "zh-TW": "JSON 格式無效。請檢查你的配置。", ja: "無効な JSON です。設定を確認してください。", ko: "잘못된 JSON입니다. 설정을 확인하세요.", fr: "JSON invalide. Veuillez vérifier votre configuration.", de: "Ungültiges JSON. Bitte überprüfen Sie Ihre Konfiguration.", es: "JSON inválido. Por favor verifica tu configuración.", ru: "Недействительный JSON. Пожалуйста, проверьте вашу конфигурацию.", pt: "JSON inválido. Por favor, verifique sua configuração." });
raw.stCacheCleared = T("Local cache cleared.", { "zh-CN": "本地缓存已清除。", "zh-TW": "本地快取已清除。", ja: "ローカルキャッシュを削除しました。", ko: "로컬 캐시를 지웠습니다.", fr: "Cache local effacé.", de: "Lokaler Cache gelöscht.", es: "Caché local limpiado.", ru: "Локальный кэш очищен.", pt: "Cache local limpo." });
raw.aboutProjectTitle = T("Hanazar Games", { "zh-CN": "哈纳扎尔工作室", "zh-TW": "哈納扎爾工作室", ja: "Hanazar Games", ko: "Hanazar Games", fr: "Hanazar Games", de: "Hanazar Games", es: "Hanazar Games", ru: "Hanazar Games", pt: "Hanazar Games" });
raw.aboutProjectDesc = T("An independent game studio built around atmosphere, strong visual identity, and worlds that feel deliberate from the first screen to the final detail. This site serves as a central archive for projects, development notes, and public-facing material around each release.", { "zh-CN": "一家以氛围感、强烈的视觉辨识度和从第一屏到最后一处细节都经过深思熟虑的世界为核心的独立游戏工作室。本网站是项目、开发笔记以及每次发布周边公开资料的中央档案库。", "zh-TW": "一家以氛圍感、強烈的視覺辨識度和從第一屏到最後一處細節都經過深思熟慮的世界為核心的獨立遊戲工作室。本網站是專案、開發筆記以及每次發布周邊公開資料的中央檔案庫。", ja: "雰囲気、強い視覚的アイデンティティ、そして最初の画面から最後のディテールまで意図的に感じられる世界を中心に構築されたインディーゲームスタジオ。このサイトは、プロジェクト、開発ノート、および各リリース周辺の公開資料の中央アーカイブです。", ko: "분위기, 강력한 시각적 정체성, 그리고 첫 화면부터 마지막 디테일까지 의도적으로 느껴지는 세계를 중심으로 구축된 인디 게임 스튜디오입니다. 이 사이트는 프로젝트, 개발 노트, 그리고 각 출시 주변 공개 자료의 중앙 아카이브입니다.", fr: "Un studio de jeux indépendant construit autour de l'atmosphère, d'une forte identité visuelle et de mondes délibérés du premier écran au dernier détail. Ce site sert d'archive centrale pour les projets, notes de développement et matériel public autour de chaque sortie.", de: "Ein unabhängiges Spielestudio, das auf Atmosphäre, starke visuelle Identität und durchdachte Welten vom ersten Bildschirm bis zum letzten Detail aufbaut. Diese Website dient als zentrales Archiv für Projekte, Entwicklungsnotizen und öffentliches Material rund um jede Veröffentlichung.", es: "Un estudio de juegos independiente construido alrededor de la atmósfera, una fuerte identidad visual y mundos deliberados desde la primera pantalla hasta el último detalle. Este sitio sirve como archivo central para proyectos, notas de desarrollo y material público alrededor de cada lanzamiento.", ru: "Независимая игровая студия, построенная вокруг атмосферы, сильной визуальной идентичности и продуманных миров с первого экрана до последней детали. Этот сайт служит центральным архивом для проектов, заметок разработки и публичных материалов вокруг каждого релиза.", pt: "Um estúdio de jogos independente construído em torno da atmosfera, forte identidade visual e mundos deliberados da primeira tela ao último detalhe. Este site serve como arquivo central para projetos, notas de desenvolvimento e material público em torno de cada lançamento." });
raw.aboutAuthor = T("Author", { "zh-CN": "作者", "zh-TW": "作者", ja: "作者", ko: "작성자", fr: "Auteur", de: "Autor", es: "Autor", ru: "Автор", pt: "Autor" });
raw.aboutAuthorName = T("Hanazar Ochikawa", { "zh-CN": "Hanazar Ochikawa", "zh-TW": "Hanazar Ochikawa", ja: "Hanazar Ochikawa", ko: "Hanazar Ochikawa", fr: "Hanazar Ochikawa", de: "Hanazar Ochikawa", es: "Hanazar Ochikawa", ru: "Hanazar Ochikawa", pt: "Hanazar Ochikawa" });
raw.aboutLinks = T("Links", { "zh-CN": "链接", "zh-TW": "連結", ja: "リンク", ko: "링크", fr: "Liens", de: "Links", es: "Enlaces", ru: "Ссылки", pt: "Links" });
raw.aboutVersion = T("Version", { "zh-CN": "版本", "zh-TW": "版本", ja: "バージョン", ko: "버전", fr: "Version", de: "Version", es: "Versión", ru: "Версия", pt: "Versão" });
raw.aboutContact = T("Contact: hanazar@mirako.co", { "zh-CN": "联系: hanazar@mirako.co", "zh-TW": "聯繫: hanazar@mirako.co", ja: "連絡先: hanazar@mirako.co", ko: "연락처: hanazar@mirako.co", fr: "Contact : hanazar@mirako.co", de: "Kontakt: hanazar@mirako.co", es: "Contacto: hanazar@mirako.co", ru: "Контакты: hanazar@mirako.co", pt: "Contato: hanazar@mirako.co" });
raw.aboutCopyright = T("Copyright © 2026 Mirako Company. Developed by Hanazar Ochikawa.", { "zh-CN": "版权所有 © 2026 Mirako Company. 开发者 Hanazar Ochikawa。", "zh-TW": "版權所有 © 2026 Mirako Company. 開發者 Hanazar Ochikawa。", ja: "Copyright © 2026 Mirako Company. Developed by Hanazar Ochikawa.", ko: "Copyright © 2026 Mirako Company. Developed by Hanazar Ochikawa.", fr: "Copyright © 2026 Mirako Company. Développé par Hanazar Ochikawa.", de: "Copyright © 2026 Mirako Company. Entwickelt von Hanazar Ochikawa.", es: "Copyright © 2026 Mirako Company. Desarrollado por Hanazar Ochikawa.", ru: "Copyright © 2026 Mirako Company. Разработано Hanazar Ochikawa.", pt: "Copyright © 2026 Mirako Company. Desenvolvido por Hanazar Ochikawa." });
raw.aboutPrivacy = T("All information on this site is stored locally. No personal data or API keys are uploaded.", { "zh-CN": "本网站所有信息均在本地保存。不会上传你的个人信息或 API 私钥。", "zh-TW": "本網站所有資訊均在本地儲存。不會上傳你的個人資訊或 API 私鑰。", ja: "このサイトのすべての情報はローカルに保存されます。個人データや API 秘密鍵はアップロードされません。", ko: "이 사이트의 모든 정보는 로컬에 저장됩니다. 개인 데이터나 API 비밀 키는 업로드되지 않습니다.", fr: "Toutes les informations de ce site sont stockées localement. Aucune donnée personnelle ou clé API privée n'est téléchargée.", de: "Alle Informationen auf dieser Website werden lokal gespeichert. Keine persönlichen Daten oder privaten API-Schlüssel werden hochgeladen.", es: "Toda la información de este sitio se almacena localmente. No se suben datos personales ni claves API privadas.", ru: "Вся информация на этом сайте хранится локально. Персональные данные и приватные API-ключи не загружаются.", pt: "Todas as informações neste site são armazenadas localmente. Nenhum dado pessoal ou chave API privada é enviada." });

// Footer link placeholders
raw.footerWorldsChars = T("Worlds & Characters", { "zh-CN": "世界与角色", "zh-TW": "世界與角色", ja: "世界とキャラクター", ko: "세계와 캐릭터", fr: "Mondes & Personnages", de: "Welten & Charaktere", es: "Mundos y Personajes", ru: "Миры и Персонажи", pt: "Mundos e Personagens" });
raw.footerUpcoming = T("Upcoming Releases", { "zh-CN": "即将发布", "zh-TW": "即將發布", ja: "近日公開", ko: "예정된 출시", fr: "Sorties à venir", de: "Kommende Veröffentlichungen", es: "Lanzamientos próximos", ru: "Предстоящие релизы", pt: "Lançamentos futuros" });
raw.footerInternalArchive = T("Internal Archive", { "zh-CN": "内部档案", "zh-TW": "內部檔案", ja: "内部アーカイブ", ko: "낶부 아카이브", fr: "Archive interne", de: "Internes Archiv", es: "Archivo interno", ru: "Внутренний архив", pt: "Arquivo interno" });
raw.footerAnnouncements = T("Announcements", { "zh-CN": "公告", "zh-TW": "公告", ja: "お知らせ", ko: "공지사항", fr: "Annonces", de: "Ankündigungen", es: "Anuncios", ru: "Объявления", pt: "Anúncios" });
raw.footerRoadmap = T("Roadmap", { "zh-CN": "路线图", "zh-TW": "路線圖", ja: "ロードマップ", ko: "로드맵", fr: "Feuille de route", de: "Roadmap", es: "Hoja de ruta", ru: "Дорожная карта", pt: "Roteiro" });
raw.footerPressKit = T("Press Kit", { "zh-CN": "媒体资料包", "zh-TW": "媒體資料包", ja: "プレスキット", ko: "볼로자료", fr: "Dossier de presse", de: "Pressekit", es: "Kit de prensa", ru: "Пресс-кит", pt: "Kit de imprensa" });
raw.footerPartnerships = T("Partnerships", { "zh-CN": "合作", "zh-TW": "合作", ja: "パートナーシップ", ko: "파트너십", fr: "Partenariats", de: "Partnerschaften", es: "Alianzas", ru: "Партнерства", pt: "Parcerias" });

// Theme labels
raw.themeDark = T("Dark", { "zh-CN": "深色", "zh-TW": "深色", ja: "ダーク", ko: "다크", fr: "Sombre", de: "Dunkel", es: "Oscuro", ru: "Темная", pt: "Escuro" });
raw.themeLight = T("Light", { "zh-CN": "浅色", "zh-TW": "淺色", ja: "ライト", ko: "라이트", fr: "Clair", de: "Hell", es: "Claro", ru: "Светлая", pt: "Claro" });
raw.themeAuto = T("Auto", { "zh-CN": "自动", "zh-TW": "自動", ja: "自動", ko: "자동", fr: "Auto", de: "Auto", es: "Auto", ru: "Авто", pt: "Auto" });

// Font labels
raw.fontDefaultSans = T("Default Sans", { "zh-CN": "默认无衬线", "zh-TW": "預設無襯線", ja: "デフォルト Sans", ko: "기본 Sans", fr: "Sans par défaut", de: "Standard Sans", es: "Sans predeterminado", ru: "Sans по умолчанию", pt: "Sans padrão" });
raw.fontSerif = T("Serif", { "zh-CN": "衬线体", "zh-TW": "襯線體", ja: "Serif", ko: "Serif", fr: "Serif", de: "Serif", es: "Serif", ru: "Serif", pt: "Serif" });
raw.fontMono = T("Monospace", { "zh-CN": "等宽", "zh-TW": "等寬", ja: "等幅", ko: "고정폭", fr: "Monospace", de: "Monospace", es: "Monospace", ru: "Monospace", pt: "Monospace" });
raw.fontRounded = T("Rounded", { "zh-CN": "圆体", "zh-TW": "圓體", ja: "丸ゴシック", ko: "둥근", fr: "Arrondi", de: "Abgerundet", es: "Redondeado", ru: "Скругленный", pt: "Arredondado" });
raw.fontCustom = T("Custom", { "zh-CN": "自定义", "zh-TW": "自訂", ja: "カスタム", ko: "사용자 지정", fr: "Personnalisé", de: "Benutzerdefiniert", es: "Personalizado", ru: "Пользовательский", pt: "Personalizado" });

// Placeholders
raw.stCustomFontPlaceholder = T("Enter font name...", { "zh-CN": "输入字体名称...", "zh-TW": "輸入字體名稱...", ja: "フォント名を入力...", ko: "폰트 이름 입력...", fr: "Entrez le nom de la police...", de: "Schriftartname eingeben...", es: "Introduzca el nombre de la fuente...", ru: "Введите название шрифта...", pt: "Digite o nome da fonte..." });

// Accessibility labels
raw.ariaSettings = T("Settings", { "zh-CN": "设置", "zh-TW": "設定", ja: "設定", ko: "설정", fr: "Paramètres", de: "Einstellungen", es: "Configuración", ru: "Настройки", pt: "Configurações" });
raw.ariaCloseSettings = T("Close settings", { "zh-CN": "关闭设置", "zh-TW": "關閉設定", ja: "設定を閉じる", ko: "설정 닫기", fr: "Fermer les paramètres", de: "Einstellungen schließen", es: "Cerrar configuración", ru: "Закрыть настройки", pt: "Fechar configurações" });
raw.ariaSettingsCategories = T("Settings categories", { "zh-CN": "设置分类", "zh-TW": "設定分類", ja: "設定カテゴリー", ko: "설정 카테고리", fr: "Catégories de paramètres", de: "Einstellungskategorien", es: "Categorías de configuración", ru: "Категории настроек", pt: "Categorias de configurações" });
raw.ariaHomepageSections = T("Homepage sections", { "zh-CN": "首页栏目", "zh-TW": "首頁欄目", ja: "ホームページセクション", ko: "홈페이지 섹션", fr: "Sections de la page d'accueil", de: "Startseitenabschnitte", es: "Secciones de la página de inicio", ru: "Разделы главной страницы", pt: "Seções da página inicial" });
raw.ariaOpenSettings = T("Open settings", { "zh-CN": "打开设置", "zh-TW": "開啟設定", ja: "設定を開く", ko: "설정 열기", fr: "Ouvrir les paramètres", de: "Einstellungen öffnen", es: "Abrir configuración", ru: "Открыть настройки", pt: "Abrir configurações" });

// Build final translations object
export const t = (() => {
  const result: Record<LangCode, Record<string, string>> = {} as any;
  const langs: LangCode[] = [
    "zh-CN", "zh-TW", "en", "ja", "ko", "fr", "de", "es", "ru", "pt",
    "it", "nl", "pl", "tr", "vi", "id", "uk", "el", "cs", "sv",
  ];
  for (const lang of langs) {
    result[lang] = {};
    for (const key of Object.keys(raw)) {
      const entry = raw[key];
      result[lang][key] = (entry as any)[lang] ?? entry.en;
    }
  }
  return result;
})();

export function getTranslation(lang: LangCode, key: string): string {
  return t[lang]?.[key] ?? t.en[key] ?? key;
}
